In [5]:
import numpy as np
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr2=np.random.rand(3,4)
arr2

array([[0.10533733, 0.85871328, 0.83481286, 0.65874206],
       [0.43195922, 0.00755715, 0.64298314, 0.05606649],
       [0.65073625, 0.29874704, 0.21051937, 0.87560071]])

In [14]:
arr3=np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result1=np.add(a,b)
result1

array([5, 7, 9])

In [24]:
result2=np.subtract(b,a)
result2

array([3, 3, 3])

In [26]:
result3=np.multiply(a,b)
result3

array([ 4, 10, 18])

In [27]:
result4=np.divide(a,b)
result4

array([0.25, 0.4 , 0.5 ])

In [29]:
result5=np.sqrt(a)
result5

array([1.        , 1.41421356, 1.73205081])

In [31]:
result6=np.mean(a)
result6

np.float64(2.0)

In [32]:
result7=np.median(a)
result7

np.float64(2.0)

In [34]:
result8=np.std(a)
result8

np.float64(0.816496580927726)

In [38]:
to_shape_arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
shaped_arr=to_shape_arr.reshape(3,4)
shaped_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr=np.array([[1,2,4],[8,10,12],[14,20,21]])
arr[0,:]


array([1, 2, 4])

In [47]:
arr[:,-1]

array([ 4, 12, 21])

In [ ]:
arr[::-1] #reverse of thr array

array([[14, 20, 21],
       [ 8, 10, 12],
       [ 1,  2,  4]])

In [ ]:
print(arr[arr>5]) #condition applying

[ 8 10 12 14 20 21]


In [ ]:
print(arr+1) #adding scalar value to 2d array

[[ 2  3  5]
 [ 9 11 13]
 [15 21 22]]


In [ ]:
frst=np.array([[1,2,4],[6,3,7]]) 
scnd=np.array([1,9,2])
print(scnd*frst) #broadcasting

[[ 1 18  8]
 [ 6 27 14]]


In [14]:
print(frst@scnd) #dot product , can also use np.dot()
print(np.dot(frst,scnd))

[27 47]
[27 47]


In [ ]:
frst=np.array([[1,2,4],[6,3,7]]) 
scnd=np.array([[2,3],[1,9],[7,8]])
product = np.matmul(frst,scnd) #matrix multiplication 
product

array([[ 32,  53],
       [ 64, 101]])

In [ ]:
print(np.linalg.det(arr)) #determinant of array

49.99999999999993


In [27]:
print(np.linalg.inv(arr))

[[-0.6   0.76 -0.32]
 [-0.   -0.7   0.4 ]
 [ 0.4   0.16 -0.12]]
